// Auto-generated by OpenTest
// Using system browser: Chrome

module.exports = {
  use: {
    channel: 'chrome', // Use system Chrome
    // Alternative: specify exact path
    // executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    
    headless: false,
    viewport: { width: 1280, height: 720 },
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
  
  timeout: 30000,
  expect: {
    timeout: 5000,
  },
};
