name: opentest

services:
  neo4j:
    image: neo4j:5.24-community
    container_name: open-test-neo4j
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
