// Testing-agent property graph. SPEC-ARCH-NEO4J-GRAPHRAG-TESTING-010

CREATE CONSTRAINT feature_id IF NOT EXISTS FOR (n:Feature) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT scenario_id IF NOT EXISTS FOR (n:Scenario) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT precondition_id IF NOT EXISTS FOR (n:PreCondition) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT action_id IF NOT EXISTS FOR (n:Action) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT state_id IF NOT EXISTS FOR (n:State) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT rule_id IF NOT EXISTS FOR (n:Rule) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT testcase_id IF NOT EXISTS FOR (n:TestCase) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT defect_id IF NOT EXISTS FOR (n:Defect) REQUIRE n.id IS UNIQUE;

CREATE FULLTEXT INDEX requirement_entry IF NOT EXISTS
FOR (n:Feature|Scenario|Rule)
ON EACH [n.name, n.description];
